In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [3]:

df = pd.read_csv('pokemon.csv')
df.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [6]:
legendry_true = df[df['is_legendary'] == True]
legendry_true.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
143,"['Pressure', 'Snow Cloak']",0.50,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,...,NaN,144,95,125,85,ice,flying,55.4,1,1
144,"['Pressure', 'Static']",0.50,1.0,1.0,1.0,1.0,0.5,1.0,0.5,1.0,...,NaN,145,125,90,100,electric,flying,52.6,1,1
145,"['Pressure', 'Flame Body']",0.25,1.0,1.0,2.0,0.5,0.5,0.5,1.0,1.0,...,NaN,146,125,85,90,fire,flying,60.0,1,1
149,"['Pressure', 'Unnerve']",2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,150,194,120,140,psychic,NaN,122.0,1,1
150,['Synchronize'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,151,100,100,100,psychic,NaN,4.0,1,1

In [11]:
# get the pokemon name from user input and get the details of the pokemon
pokename = input()

Mew

In [12]:
poke = df[df['name'] == pokename]
poke.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
150,['Synchronize'],2.0,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,151,100,100,100,psychic,NaN,4.0,1,1

In [20]:
# find pokemon with maximum base_tatal and if tie exist check if legendry is true
maxbasetotal = df[df['base_total'] == df['base_total'].max()]

# if tie exist then check if legendry is true
maxbasetotal = maxbasetotal[maxbasetotal['is_legendary'] == True]
#still tie exit then check generation = 3
maxbasetotal = maxbasetotal[maxbasetotal['generation'] == 3]



maxbasetotal.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
383,['Air Lock'],0.5,1.0,2.0,1.0,2.0,0.5,0.5,1.0,1.0,...,NaN,384,180,100,115,dragon,flying,206.5,3,1

Warning: Total number of columns (41) exceeds max_columns (20) limiting to first (20) columns.

In [21]:
# find those values of which generation = 6
gen6 = df[df['generation'] == 6]
gen6.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
649,"['Overgrow', 'Bulletproof']",2.0,1.0,1.0,0.5,1.0,1.0,2.0,2.0,1.0,...,88.1,650,48,45,38,grass,NaN,9.0,6,0
650,"['Overgrow', 'Bulletproof']",2.0,1.0,1.0,0.5,1.0,1.0,2.0,2.0,1.0,...,88.1,651,56,58,57,grass,NaN,29.0,6,0
651,"['Overgrow', 'Bulletproof']",1.0,0.5,1.0,0.5,2.0,1.0,2.0,4.0,1.0,...,88.1,652,74,75,64,grass,fighting,90.0,6,0
652,"['Blaze', 'Magician']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,653,62,60,60,fire,NaN,9.4,6,0
653,"['Blaze', 'Magician']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,654,90,70,73,fire,NaN,14.5,6,0